version: 2.1
orbs:
  microscanner: 'aquasecurity/microscanner@dev:0.1.1'
jobs:
  docker-build:
    executor: microscanner/default
    steps:
      - checkout
      - run: 'docker pull alpine:latest .'
workflows:
  scan-image:
    jobs:
      - docker-build
      - microscanner/scan-image:
          requires:
            - docker-build
          context: myContext
          image: 'alpine:latest'